[global]
error_log = /dev/stderr
;request_terminate_timeout = 1h

[www]
access.log = /dev/stdout
listen = 9000

clear_env = no

; Ensure worker stdout and stderr are sent to the main error log.
catch_workers_output = yes
